spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
  jpa:
    showSql: true
    hibernate:
      formatSql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    com.example.demo: TRACE

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false